<?php
declare(strict_types=1);

/**
 * ReportingCloud PHP SDK
 *
 * PHP SDK for ReportingCloud Web API. Authored and supported by Text Control GmbH.
 *
 * @link      https://www.reporting.cloud to learn more about ReportingCloud
 * @link      https://git.io/Jejj2 for the canonical source repository
 * @license   https://git.io/Jejjr
 * @copyright © 2020 Text Control GmbH
 */

namespace TxTextControlTest\ReportingCloud\Stdlib;

use TxTextControlTest\ReportingCloud\AbstractReportingCloudTest;
use TxTextControl\ReportingCloud\Stdlib\ArrayUtils;

/**
 * Class ArrayUtilsTest
 *
 * @package TxTextControlTest\ReportingCloud
 * @author  Jonathan Maron (@JonathanMaron)
 */
class ArrayUtilsTest extends AbstractReportingCloudTest
{
    private function getTestData(): array
    {
        return [
            'a' => 'a',
            'b' => 'b',
            'c' => 'c',
            'd' => [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
            ],
        ];
    }

    private function getTestFilename(): string
    {
        $filename = tempnam(sys_get_temp_dir(), hash('sha256', __CLASS__));

        return (string) $filename;
    }

    public function testVarExportToFile(): void
    {
        $filename = $this->getTestFilename();
        $array    = $this->getTestData();

        ArrayUtils::varExportToFile($filename, $array);

        $this->assertEquals($array, include $filename);

        unlink($filename);
    }

    public function testVarExportToFileWithGenerator(): void
    {
        $filename = $this->getTestFilename();
        $array    = $this->getTestData();

        ArrayUtils::varExportToFile($filename, $array, 'My-Generator');

        $buffer = (string) file_get_contents($filename);

        $this->assertStringContainsString('File generated by My-Generator.', $buffer);
        $this->assertStringContainsString('Do not edit.', $buffer);

        unlink($filename);
    }
}
