<?php

namespace TxTextControlTest\ReportingCloud\Stdlib;

use PHPUnit\Framework\TestCase;
use TxTextControl\ReportingCloud\Stdlib\ArrayUtils;

class ArrayUtilsTest extends TestCase
{
    private function getTestData()
    {
        return [
            'a' => 'a',
            'b' => 'b',
            'c' => 'c',
            'd' => [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
            ],
        ];
    }

    private function getTestFilename()
    {
        $filename = tempnam(sys_get_temp_dir(), hash('sha256', __CLASS__));

        return $filename;
    }

    public function testVarExportToFile()
    {
        $filename = $this->getTestFilename();
        $array    = $this->getTestData();

        $result = ArrayUtils::varExportToFile($filename, $array);

        $this->assertIsInt($result);

        $this->assertEquals($array, include $filename);

        unlink($filename);
    }

    public function testVarExportToFileWithGenerator()
    {
        $filename = $this->getTestFilename();
        $array    = $this->getTestData();

        $result = ArrayUtils::varExportToFile($filename, $array, 'My-Generator');

        $this->assertIsInt($result);

        $buffer = file_get_contents($filename);

        $this->assertContains('File generated by My-Generator.', $buffer);
        $this->assertContains('Do not edit.', $buffer);

        unlink($filename);
    }
}
